theme = "catppuccin_mocha_transparent"

[editor]
color-modes = true
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# yazi configuration taken from https://github.com/helix-editor/helix/discussions/12934
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

