[[language]]
name = "python"
auto-format = true 
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = [{ name = "pyright"}]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"] 
config = {}

[[language]]
name = "c"
formatter = { command = "clang-format" }
auto-format = true
