[[language]]
name = "python"
auto-format = true 
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = [{ name = "pyright"}]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"] 
config = {}

[[language]]
name = "c"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }
auto-format = false 
# don't autoformat json by default 
# since it can blow in size 
# and usually are not read by human except for debbugging

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }
auto-format = true
language-servers = ["ltex-ls"]

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
auto-format = true
