[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
auto-format = true 
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = ["format", "-" ] }

[[language]]
name = "c"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "cpp"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }
auto-format = false 
# don't autoformat json by default 
# since it can blow in size 
# and usually are not read by human except for debbugging

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }
auto-format = true
language-servers = ["ltex-ls"]

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
auto-format = true

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "yamlfmt", args = ["-"] }

[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist", "ltex-ls"]
auto-format = true
formatter = { command = "typstyle", args=["--wrap-text"] }
